[package]
name = "vulkayes-core"
version = "0.1.0"
authors = ["edward"]
edition = "2018"

[features]
default = []

rust_host_allocator = []
no_atomics = []

[dependencies]
# core
# We use git repository because the published crate seems to be quite outdated
ash = { git = "https://github.com/MaikKlein/ash", rev = "98def0a4e3c5f962f0cd50086700cacfcee1c62b" }

# utility
arrayvec = "0.5"

# performance
rustc-hash = "1"

# debuging
log = "0.4"
thiserror = "1"

[dev-dependencies]
edwardium_logger = "1"