[package]
name = "vulkayes-core"
version = "0.1.0"
authors = ["edward"]
edition = "2018"

[features]
default = []

rust_host_allocator = []
non_atomic_vrc = []

[dependencies]
# core
ash = "0.29"

# utility
arrayvec = "0.5"

# performance
rustc-hash = "1"

# debuging
log = "0.4"
thiserror = "1"

[dev-dependencies]
edwardium_logger = "1"